server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/userdb
    username: postgres
    password: postgres
  data:
    redis:
      host: redis
      port: 6379
    mongodb:
      uri: mongodb://mongoadmin:secret@mongodb:27017/user-logs-db?authSource=admin
      database: user-logs-db
  application:
    name: user-service
  cache:
    type: redis
